---
- name: Install MySQL server
  apt:
    name: mysql-server
    state: present

- name: Ensure MySQL is running
  service:
    name: mysql
    state: started
    enabled: yes

- name: Set root password
  mysql_user:
    login_user: root
    login_password: ""
    user: root
    password: "{{ mysql_root_password }}"
    host_all: yes
  ignore_errors: yes

- name: Create WordPress database
  mysql_db:
    name: "{{ mysql_wp_db }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Create WordPress DB user
  mysql_user:
    name: "{{ mysql_wp_user }}"
    password: "{{ mysql_wp_pass }}"
    priv: "{{ mysql_wp_db }}.*:ALL"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
