version: "3"

services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.16.3
    command: filebeat -strict.perms=false
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=localhost
    volumes:
      - "applicationLogPath:/mnt/log:ro"
      - "./filebeat.docker.yml:/usr/share/filebeat/filebeat.yml"  
      - "fbdata:/usr/share/filebeat/data/"
      - "./logs:/var/log/filebeat"
        
volumes:
  fbdata: 
    driver: local 
  applicationLogPath: 
    external: true
    driver: local 