version: '3.4'

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    container_name: es01
    environment:
      - node.name=es01
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  kib01:
    image: docker.elastic.co/kibana/kibana:${ELK_VERSION}
    container_name: kib01
    depends_on:
      - es01
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=["http://es01:9200"]
    networks:
      - elastic
    volumes:
      - kibanaconfig:/usr/share/kibana/config/
      - kibanadata:/usr/share/kibana/data

networks:
  elastic:
    driver: bridge

volumes:
  kibanaconfig: 
    driver: local
  kibanadata:
    driver: local
  data01:
    driver: local
