---
name: OTBR
services:
  matter-server:
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    container_name: matter-server
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - /mnt/docker-data/matter:/data

  otbr:
    image: openthread/border-router:latest
    container_name: otbr
    restart: unless-stopped
    network_mode: "host"
    environment:
      # Disable start scritps that requires iptables annd modify routing tables. This is required for running in a unprivileged container.
      - NAT64=0 
      - NAT44=0
      - DNS64=0
      - FIREWALL=0
      # configure the OTBR to use the serial interface of the host for the Thread radio
      - OT_RCP_DEVICE=spinel+hdlc+uart:///dev/ttyUSB-Thread?uart-baudrate=460800
      - OT_INFRA_IF=eth0
      - OT_THREAD_IF=wpan0
      - OT_LOG_LEVEL=7
      - WEB_GUI=1
      - REST_API=1
      # --- Expose services outside 127.0.0.1 ---
      - OT_REST_LISTEN_ADDR=0.0.0.0
      - OT_WEB_LISTEN_ADDR=0.0.0.0
    devices:
      - /dev/ttyUSB-Thread:/dev/ttyUSB-Thread
      - /dev/net/tun:/dev/net/tun # <-- Add module of virtual interfaces
    cap_add:
      - NET_ADMIN # <-- Change: Permission to create wpan0 interface
    ports:
      - "8080:80"     # Web GUI 
      - "8081:8081"   # REST API 
    group_add:
      - 20 # dialout group
    volumes:
      - /mnt/docker-data/otbr:/data
