version: "3.8"

services:
  sonoff-dongle-flasher:
    image: ewelink/sonoff-dongle-flasher:latest
    container_name: sonoff-dongle-flasher
    ports:
      - "8324:8324"            # Web console
    privileged: true
    volumes:
      - sonoff_data:/workspace/data  # Persistent config/firmware
      - /run/udev:/run/udev:ro       # Auto-discovery
    restart: unless-stopped    
    devices:
      - /dev/ttyUSB-Thread:/dev/ttyUSB-Thread
      - /dev/ttyUSB-Zigbee:/dev/ttyUSB-Zigbee

volumes:
  sonoff_data:
