version: "2.1"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1005
      - PGID=100
      - TZ=Europe/Warsaw
    volumes:
      - config:/config      
    restart: unless-stopped
    networks:
      - ngproxy
      
volumes:
  config:

networks:
  ngproxy:
    external:
      name: ngproxy
