---
- name: Deploy portainer agent to Docker Bind Mount
  hosts: portainer_agents
  become: true
  vars:
    # Update this to the absolute path of your bind-mounted HA config directory
    ha_config_dir: "/mnt/docker-data/portainer"
    # Update this if your docker compose service or container has a different name
    ha_container_name: "portainer"

  tasks:
    - name: Ensure the Portainer config directory exists
      file:
        path: "{{ ha_config_dir }}"
        state: directory
        owner: "root"
        group: "root"

    - name: Copy docker-compose.homelab.yml for Portainer Agent
      copy:
        src: "../../../Portainer/Agent/docker-compose.homelab.yml"
        dest: "{{ ha_config_dir }}/docker-compose.yml"
        mode: '0644'
      
    - name: Deploy Portainer Agent using Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ ha_config_dir }}"
        state: present