---
name: homeassistant
services:
  homeassistant:
    container_name: homeassistant
    networks:
      homeassistant: {}
      vlan100: 
        ipv4_address: 192.168.100.18
      wifi: 
        ipv4_address: 192.168.11.11
        ipv6_address: fd00:11::11
    image: ghcr.io/home-assistant/home-assistant:2026.6
    depends_on:
      - mqtt
      - zigbee2mqtt
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # Use the Home Assistant configuration directory on /mnt/docker-data/home-assistant/config on the host to persist the Home Assistant configuration and data
      - /mnt/docker-data/home-assistant/config:/config
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    restart: unless-stopped
    ports:
      - 80:8123
  mqtt:
    container_name: mqtt
    networks:
      - homeassistant
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # Use the MQTT data directory on /mnt/docker-data/mqtt/data on the host to persist the MQTT configuration and data
      - /mnt/docker-data/mqtt:/mosquitto
    # ports:
      #- 1883:1883
      #- 9001:9001
    command: mosquitto -c /mosquitto-no-auth.conf

  zigbee2mqtt:
    container_name: zigbee2mqtt
    networks:
      # Add the container to the IOT network
      - homeassistant
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    restart: unless-stopped
    image: ghcr.io/koenkk/zigbee2mqtt:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # Use the Zigbee2MQTT data directory on /mnt/docker-data/zigbee2mqtt/data on the host to persist the Zigbee2MQTT configuration and data
      - /mnt/docker-data/zigbee2mqtt/data:/app/data
    ports:
      - 8080:8080
    group_add:
      - dialout
    user: 1000:1000
    devices:
      # Pass the Zigbee adapter through to the container using the --device flag
      - /dev/ttyUSB-Zigbee:/dev/ttyUSB-Zigbee

  matter-server:
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    container_name: matter-server
    restart: unless-stopped
    networks:
      homeassistant: {}
      vlan100: 
        ipv4_address: 192.168.100.17
      wifi: 
        ipv4_address: 192.168.11.12
        ipv6_address: fd00:11::12
    volumes:
      - /mnt/docker-data/matter:/data

  otbr:
    image: openthread/border-router:latest
    container_name: otbr
    restart: unless-stopped
    networks:
      homeassistant: {}
      vlan100: 
        ipv4_address: 192.168.100.16
      wifi: 
        ipv4_address: 192.168.11.13
        ipv6_address: fd00:11::13
    environment:
      # Disable start scritps that requires iptables annd modify routing tables. This is required for running in a unprivileged container.
      - NAT64=0 
      - NAT44=0
      - DNS64=0
      - FIREWALL=0
      # configure the OTBR to use the serial interface of the host for the Thread radio
      - OT_RCP_DEVICE=spinel+hdlc+uart:///dev/ttyUSB-Thread?uart-baudrate=460800
      - OT_INFRA_IF=eth0
      - OT_THREAD_IF=wpan0
      - WEB_GUI=1
      - REST_API=1
      # --- Expose services outside 127.0.0.1 ---
      - OT_REST_LISTEN_ADDR=0.0.0.0
      - OT_WEB_LISTEN_ADDR=0.0.0.0
    devices:
      - /dev/ttyUSB-Thread:/dev/ttyUSB-Thread
      - /dev/net/tun:/dev/net/tun # <-- Add module of virtual interfaces
    cap_add:
      - NET_ADMIN # <-- Change: Permission to create wpan0 interface
    ports:
      - "8080:80"     # Web GUI 
      - "8081:8081"   # REST API 
    group_add:
      - 20 # dialout group
    volumes:
      - /mnt/docker-data/otbr:/data

networks:
  homeassistant:
    name: homeassistant
  vlan100: 
    external: true
    name: docker-static-vlan100
  wifi: 
    external: true
    name: docker-static-wifi