---
# APT Does not work on Ubuntu 20.04
- name: Install python3-apt
  ansible.builtin.raw: apt-get install -y python3-apt
  become: true

- name: Update apt cache
  ansible.builtin.raw: apt-get update
  become: true
  # apt:
  #   update_cache: yes

- name: Install base packages
  ansible.builtin.raw: apt-get install -y curl unzip git software-properties-common rsync
  become: true
  # apt:
  #   name:
  #     - curl
  #     - unzip
  #     - git
  #     - software-properties-common
  #   state: present

- name: Set timezone
  timezone:
    name: Europe/Warsaw
