---
- hosts: web
  become: yes
  tasks:

  - name: Sync WordPress files
    synchronize:
      src: "/mnt/BlogBackups/Restore/html/"
      dest: "/var/www/html/"
      recursive: yes
      delete: no

  - name: Fix permissions
    file:
      path: /var/www/html
      owner: www-data
      group: www-data
      recurse: yes

- hosts: db
  become: yes
  tasks:

  - name: Import SQL dump
    mysql_db:
      name: wordpress
      state: import
      target: "/mnt/BlogBackups/Restore/dump.sql"
      login_user: root
      login_password: "rootpass"
