version: '3.4'

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    env_file:
      - .env
    environment:
      - xpack.monitoring.enabled=true
      - xpack.monitoring.collection.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    networks:
      - elastic

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.16.3
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    env_file:
      - .env
    environment:
      - ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]
      - monitoring.ui.container.elasticsearch.enabled=true
    networks:
      - elastic

networks:
  elastic:
    driver: bridge

volumes:
  elasticsearch-data: null
