---
- name: Remove default index.html
  file:
    path: {{ web_root }}/index.html
    state: absent

- name: Extract WordPress
  unarchive:
    src: wordpress-{{ wp_version }}.tar.gz
    dest: {{ web_root }}
    remote_src: yes
    extra_opts: [ "--strip-components=1" ]

- name: Set permissions
  file:
    path: {{ web_root }}
    owner: www-data
    group: www-data
    recurse: yes
