version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: always
    networks:
      qnet-static:
        ipv4_address: 192.168.50.8
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "444:443/tcp"
    environment:
      TZ: 'Europe/Warsaw'
      PIHOLE_DNS_: 1.1.1.1;1.0.0.1
      VIRTUAL_HOST: pi.hole
      FTLCONF_LOCAL_IPV4: 192.168.50.8
      # WEBPASSWORD: 'set a secure password here or it will be random'
      WEBPASSWORD: $WEBPASSWORD
    dns:
      - 1.1.1.1
      - 8.8.8.8
    # Volumes store your data between container upgrades
    volumes:
      - databases:/etc/pihole/
      - dnsdata:/etc/dnsmasq.d/
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    # cap_add:
    #   - NET_ADMIN
       
volumes:
   databases:
   dnsdata: 
       
networks:
  qnet-static:
    name: docker-static-bond0
    external: true