[homeassistant]
192.168.100.14
; TODO add user on that host to connect to it. 

[homeassistant:vars]
ansible_user=ansible_mgr
ansible_ssh_private_key_file=~/.ssh/id_ansible
; ansible_python_interpreter=/usr/bin/python3.9
; ansible_apt_python_interpreter=/usr/bin/python3.9
auto_install_module_deps=true