# Newer add one IP address to more than two groups. 
# As variable squashing are merged in ASCII order.
# Even If variable is in different group that is not executed
# ansible WILL use last loaded value for that host :/
# https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#how-variables-are-merged  

# New host provisioning 
[new] 
192.168.50.100

[new:vars]
ansible_user=root
; ansible_user=root
;ansible_password= ; use -k to ask for password
;ansible_become_pass= ; use -K to ask for password if not root.

[malina]
rpi_ups ansible_host=192.168.50.20 
[malina:vars]
ansible_user=ansible_mgr
ansible_ssh_private_key_file=~/.ssh/id_ansible

[testing]
192.168.50.51
192.168.50.52
192.168.50.60
192.168.50.61

# [testing:vars]
# remote_user=ansible
# ansible_user=ansible
# ansible_become_user=root
# ansible_ssh_private_key_file= ~/.ssh/id_rsa
# ansible_become_method = su
; ansible_python_interpreter= /usr/bin/python3

[lxc]
192.168.50.11
192.168.50.12
192.168.50.13

[lxc:vars]
ansible_user=ansible_mgr
ansible_become_user=root 
ansible_ssh_private_key_file=~/.ssh/id_ansible
ansible_become_method = su

##################
; Danger ZONE! 
[proxmox] 
192.168.50.5
192.168.50.6

[proxmox:vars]
ansible_user=notset
ansible_ssh_private_key_file=~/.ssh/id_rsa

[qnap]
192.168.50.247

[qnap:vars]
ansible_user=notset
ansible_ssh_private_key_file=~/.ssh/id_rsa

[homeassistant]
192.168.100.14

[homeassistant:vars]
ansible_user=ansible_mgr
ansible_ssh_private_key_file=~/.ssh/id_ansible
; ansible_python_interpreter=/usr/bin/python3.9
; ansible_apt_python_interpreter=/usr/bin/python3.9
auto_install_module_deps=true